In [1]:
import numpy as np


Create a 1D NumPy array with values from 0 to 20 (inclusive), with a step of 2.

In [6]:
array=np.arange(0,21,2)
print(array)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [20]:
#Create a 3x3 matrix with all elements as 5.
array=np.full((3,3),5)
print(array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [24]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
add=arr1+arr2
print(add)
print("Multiplt")
mul=arr1*arr2
print(mul)
dot=np.dot(arr1,arr2)
print(dot)

[5 7 9]
Multiplt
[ 4 10 18]
32


In [32]:
arr=np.arange(10)

print(arr)
slice=arr[:5]
print(slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [33]:
'''Given a NumPy array a = np.array([1, 2, 3, 4]) and a scalar 5, add the scalar to the array using broadcasting'''
a = np.array([1, 2, 3, 4])
scalar = 5
# Add the scalar to the array using broadcasting
result = a + scalar
print(result)

[6 7 8 9]


In [41]:
arr=np.random.randint(1,101,size=10)
print(arr)
mean=np.mean(arr)
print(mean)
median=np.median(arr)
print()
print(median)
std=np.std(arr)
print()
print(std)

[ 72  40   7  88  54  46  35  29  84 100]
55.5

50.0

28.15759222660915


In [42]:
import pandas as pd

In [88]:
df=pd.DataFrame({"name":['Ramesh','Rahul','Rakesh'],'age':[20,21,24],'city':['Bhopal','Indore','Rewa']})
print(df)
print()
print("Age wali colmn")
df1= df['age']
print(df1)

df2= df[df['name']=='Rakesh']
print(df2)

df4=df['age'].mean()
print(df4)
df['age']=df['age'].fillna(df4)
print(df)

     name  age    city
0  Ramesh   20  Bhopal
1   Rahul   21  Indore
2  Rakesh   24    Rewa

Age wali colmn
0    20
1    21
2    24
Name: age, dtype: int64
     name  age  city
2  Rakesh   24  Rewa
21.666666666666668
     name  age    city
0  Ramesh   20  Bhopal
1   Rahul   21  Indore
2  Rakesh   24    Rewa


In [14]:
import pandas as pd

# Create data for the DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Designation': ['Manager', 'Engineer', 'Analyst', 'Developer', 'HR'],
    'Salary': [75000, 60000, 55000, 50000, 45000]  # Integer values for salary
}

# Create the DataFrame
df = pd.DataFrame(data)

# Print every third row
third_row = df.iloc[::3]  # Step size of 3 to get every third row

# Display the result
print(third_row)


    Name Designation  Salary
0  Alice     Manager   75000
3  David   Developer   50000
